[general]
server_check_url = http://www.gstatic.com/generate_204
network_check_url = http://bing.com
dns_exclusion_list = *.cmpassport.com, *.jegotrip.com.cn, *.icitymobile.mobi, *.alipay.com, *.tmall.com, *.qq.com, id6.me

[dns]
no-ipv6
no-system
server = 223.5.5.5
server = 119.29.29.29
doh-server = https://doh.pub/dns-query

[policy]
# 自动测速（按延迟选最优节点）
static=Hong Kong, resource-tag-regex=.*, server-tag-regex=🇭🇰|HK|Hong|hong|香港, img-url=https://raw.githubusercontent.com/mythos404/qx-icons/main/us.png
static=Taiwan, resource-tag-regex=.*, server-tag-regex=🇹🇼|TW|Taiwan|台湾|台灣,


# 手动选择
static=Singapore, resource-tag-regex=.*, server-tag-regex=🇸🇬|SG|Singapore|新加坡, img-url=https://raw.githubusercontent.com/mythos404/qx-icons/main/ab.png
static=United States, resource-tag-regex=.*, server-tag-regex=🇺🇸|US|USA|美国, img-url=https://raw.githubusercontent.com/mythos404/qx-icons/main/us.png

[server_remote]

[filter_remote]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Apple/Apple.list, tag=Apple, force-policy=direct, update-interval=86400, opt-parser=false, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Netflix/Netflix.list, tag=Netflix, force-policy=Singapore, update-interval=86400, opt-parser=false, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Spotify/Spotify.list, tag=Spotify, force-policy=direct, update-interval=86400, opt-parser=false, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Google/Google.list, tag=Google, force-policy=United States, update-interval=86400, opt-parser=false, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Claude/Claude.list, tag=Claude, force-policy=United States, update-interval=86400, opt-parser=false, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/OpenAI/OpenAI.list, tag=OpenAI, force-policy=United States, update-interval=86400, opt-parser=false, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Gemini/Gemini.list, tag=Gemini, force-policy=United States, update-interval=86400, opt-parser=false, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/YouTube/YouTube.list, tag=YouTube, force-policy=United States, update-interval=86400, opt-parser=false, enabled=true

FILTER_REGION, tag=CN, force-policy=direct, inserted-resource=true, enabled=true
FILTER_LAN, tag=LAN, force-policy=direct, inserted-resource=true, enabled=true

[filter_local]
# APNs 推送走代理（解决国内推送延迟/掉线）
host-suffix, push.apple.com, Proxy
host-keyword, courier, Proxy

# 兜底
geoip, cn, direct
final, Proxy

[server_local]

[rewrite_local]

[rewrite_remote]

[task_local]

[http_backend]

[mitm]
passphrase = 
